kind: ReplicaSet
apiVersion: apps/v1
metadata:
  name: nginx-replicasets
  namespace: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx

  template:
    metadata:
      name: nginx-rep-pod
      labels:
        app: nginx
    
    spec:
      containers:
      -  name: nginx
         image: nginx:latest
         ports:
         - containerPort: 80  

      


